### PR TITLE
Add draft explainer

### PR DESCRIPTION
**Pull request by RByers**
A first-cut (draft) of an initial explainer trying to cover the key requirements and design elements. This is just a starting place for further discussion.

### CODE REVIEW

**Comment by RByers** [comment]
@marcoscaceres WDYT of this as an initial cut at an explainer for discussion at IIW tomorrow?

**Review by marcoscaceres — APPROVED** [review]
LGTM

**Comment by marcoscaceres** [comment]
I think we should go ahead and merge this, as it will be nice to point to people during the conference.

**Review by samuelgoto — APPROVED** [review]
LGTM++

**Pull request merged**
