### PR TITLE
Chore: add .github/PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #64: Add a PULL_REQUEST_TEMPLATE.md
It would be good if we had a template with check that we need to do before we can merge a Pull Request.

This is what we use for Web Manifest: 
https://github.com/w3c/manifest/blob/main/.github/PULL_REQUEST_TEMPLATE.md

This is what the WHATWG uses:
https://github.com/whatwg/html/blob/main/PULL_REQUEST_TEMPLATE.md

What's important is that we try to implement (and add some tests for) as much as we can as we spec this out.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #64

### CODE REVIEW

**Review by OR13 — APPROVED** [review]

**Review by samuelgoto — COMMENTED** [review]
Can you help me understand what this does? Is this a template that is used by ALL PRs?

**Comment by tplooker** [comment]
> Can you help me understand what this does? Is this a template that is used by ALL PRs?

Yeap thats my understanding.

**Comment by marcoscaceres** [comment]
Yes, but we delete just ignore it for "chore" and "editorial" changes. It's only for substantive changes.

**Comment by marcoscaceres** [comment]
@samuelgoto, did the explanation make sense? A more extensive explanation/rationale is:
https://whatwg.org/working-mode#changes

The template enforces the above.

**Review by samuelgoto — APPROVED** [review]

**Comment by samuelgoto** [comment]
That makes sense to me. Approving.

**Pull request merged**
